services:
  mariadb:
    image: mariadb:11
    container_name: manga-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123       
      MYSQL_DATABASE: mangastore              
      MYSQL_USER: manga_user
      MYSQL_PASSWORD: userpass123
    ports:
      - "3306:3306"                            
    volumes:
      - mariadb_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

volumes:
  mariadb_data:
